#PBS -N ILP
#PBS -l nodes=1:ppn=4
#PBS -l walltime=5:00:00
#PBS -l mem=32gb
#PBS -q coc-force
#PBS -j oe
#PBS -o ILPlog.out
#PBS -m abe                            
#PBS -M zzhang834@gatech.edu  

# change according to the job submission requirement of your cluster

cd $PBS_O_WORKDIR
module load anaconda3 gurobi
export PYTHONPATH=$GUROBI_HOME/lib/python3.7_utf32:$PYTHONPATH
echo "start running"
python3 run_ILP_for_sim.py
